In [1]:
3 - 2

[1] 1

In [2]:
4^2

[1] 16

In [3]:
4*pi

[1] 12.56637

In [4]:
sin(4)

[1] -0.7568025

In [9]:
!(3 == 4)

[1] TRUE

In [11]:
(4==4) && (3>12)

[1] FALSE

# Variable Assignment

In [13]:
a <- (3+3)

### The Vector 

In [14]:
dat <- c(4,5,6,23,2)

In [15]:
print(dat)

[1]  4  5  6 23  2


In [16]:
v1 <- c(1,2,3)
v2 <- c(5,4,3)
v <- c(v1,v2)

In [17]:
print(v)

[1] 1 2 3 5 4 3


In [18]:
my_vec <- rep(0,10)

In [19]:
print(my_vec)

 [1] 0 0 0 0 0 0 0 0 0 0


In [20]:
m <- 1:20

In [24]:
v3 <- seq(-10,10, 2)

In [26]:
print(v3)

 [1] -10  -8  -6  -4  -2   0   2   4   6   8  10


In [27]:
v3

[1] -10  -8  -6  -4  -2   0   2   4   6   8  10

In [28]:
print(seq(-10,10,2))

 [1] -10  -8  -6  -4  -2   0   2   4   6   8  10


### Create a vector (u) with the integers from -2 to 2

In [29]:
u <- (-2,2)

ERROR: Error in parse(text = x, srcfile = src): <text>:1:9: unexpected ','
1: u <- (-2,
            ^


In [30]:
u <- (-2:2)

In [31]:
print (u)

[1] -2 -1  0  1  2


In [32]:
u <- seq (-2,2) 

In [33]:
print (u)

[1] -2 -1  0  1  2


In [1]:
v <- rnorm(5)

In [2]:
print (v)

[1] -0.3039027 -1.7174464 -0.1071206 -0.7876513 -1.1116752


In [3]:
v[2]

[1] -1.717446

In [4]:
v[1:3]

[1] -0.3039027 -1.7174464 -0.1071206

In [5]:
v[2:5]

[1] -1.7174464 -0.1071206 -0.7876513 -1.1116752

In [6]:
v[c(1,3)]

[1] -0.3039027 -0.1071206

In [7]:
print(v)

[1] -0.3039027 -1.7174464 -0.1071206 -0.7876513 -1.1116752


In [8]:
v[-3]

[1] -0.3039027 -1.7174464 -0.7876513 -1.1116752

In [10]:
indces <- c(1,3)
print(indces) 
v[indces]

[1] 1 3


[1] -0.3039027 -0.1071206

### Assignment with Indexing 

In [11]:
u <- c(5,6,8,22)

In [12]:
u[1] <- 0 

In [13]:
print (u)

[1]  0  6  8 22


In [15]:
u3 <- u[1:3]

In [16]:
print(u3)

[1] 0 6 8


### Q2: create vector (v) with three elements, 10, 20 and 30. Use indexing to change the alue of the first two elements to be 0.

In [17]:
v <- (10,20,30)

ERROR: Error in parse(text = x, srcfile = src): <text>:1:9: unexpected ','
1: v <- (10,
            ^


In [18]:
v <- (10, 20, 30)

ERROR: Error in parse(text = x, srcfile = src): <text>:1:9: unexpected ','
1: v <- (10,
            ^


In [19]:
v <- c (10,20,30)

In [20]:
print (v)

[1] 10 20 30


In [21]:
c[1] <- 0 
c[2] <- 0 

ERROR: Error in c[1] <- 0: object of type 'builtin' is not subsettable


In [22]:
v[1:2] <- 0 

In [23]:
print (v)

[1]  0  0 30


In [24]:
v[1] <- 0 
v[2] <- 0 
print (v)

[1]  0  0 30


### Create a vector, v1, with 5 elements, 10,20,30,40,50. Use indexing to get the first third and fifth from that vector and put them in a new vector (v2)

In [25]:
v1 <- c(10,20,30,40,50)

In [26]:
print(v1)

[1] 10 20 30 40 50


In [27]:
v2 <- v1(1,3,5)

ERROR: Error in v1(1, 3, 5): could not find function "v1"


In [28]:
v2 <- v1[1,3,5]

ERROR: Error in v1[1, 3, 5]: incorrect number of dimensions


In [29]:
v2 <- v1(1,3,5)

ERROR: Error in v1(1, 3, 5): could not find function "v1"


In [30]:
v2 <- v1[1,3,5]

ERROR: Error in v1[1, 3, 5]: incorrect number of dimensions


In [31]:
v2 <- c(v1(1,3,5))

ERROR: Error in v1(1, 3, 5): could not find function "v1"


In [32]:
v2 <- c(v1[1,3,5])

ERROR: Error in v1[1, 3, 5]: incorrect number of dimensions


In [33]:
v2 <- v1[c(1,3,5)]

In [34]:
print (v2)

[1] 10 30 50


In [35]:
idx <- c(1,3,5)
v2 <- v1[idx]
print(v2)

[1] 10 30 50


In [42]:
v1 <- seq(10,50,10)  ## this is creating a vector, 10-50, difference 10; 10,20,30,40,50
idx <- c(TRUE, FALSE, TRUE, FALSE, TRUE)
v2 <- v1[idx]
print (v2)

[1] 10 30 50


## Vectorization ot operations

In [37]:
v <- c(44,55,66)
v - 20 

[1] 24 35 46

In [38]:
v * 2 

[1]  88 110 132

In [39]:
v / 5 

[1]  8.8 11.0 13.2

In [40]:
v > 50 

[1] FALSE  TRUE  TRUE

### Useful Operations on Vectors 

In [43]:
v <- rnorm(10)

In [44]:
print(v)

 [1]  0.9713482 -1.6639071  0.2028088  1.8331328  0.6671331 -1.3233275
 [7]  0.2676175 -0.1262351  0.1103008 -0.7812364


In [45]:
length(v)

[1] 10

In [46]:
n <- length (v)

In [47]:
print (n)

[1] 10


In [48]:
sum (v)

[1] 0.1576351

In [49]:
max(v)

[1] 1.833133

In [50]:
min(v)

[1] -1.663907

In [51]:
mean(v)

[1] 0.01576351

In [52]:
sd(v)

[1] 1.055011

In [53]:
xbar <- mean(v)

In [54]:
print (xbar)

[1] 0.01576351


In [55]:
s <- sd(v)

In [56]:
print (s)

[1] 1.055011


### The Matrix

In [57]:
x1 <- c(4,5,6)
x2 <- c(55,55,77)

In [59]:
m <- cbind(x1,x2)
print(m)           #  m is a 3*2 matrix

     x1 x2
[1,]  4 55
[2,]  5 55
[3,]  6 77


In [60]:
m2 <- rbind(x1,x2)

In [61]:
print (m2)

   [,1] [,2] [,3]
x1    4    5    6
x2   55   55   77


In [62]:
a <- matrix(0, nrow=3, ncol=3)

In [63]:
print (a)

     [,1] [,2] [,3]
[1,]    0    0    0
[2,]    0    0    0
[3,]    0    0    0


In [64]:
dat <- rnorm (15)

In [65]:
b <- matrix(dat, ncol=3)

In [66]:
print(b)

           [,1]       [,2]       [,3]
[1,] -1.5879961  0.7695164  0.3928078
[2,]  0.2484681 -1.1434928  0.2350661
[3,]  0.9247560 -0.7085367  1.9200839
[4,] -0.5925383  0.4541996 -1.2570366
[5,]  0.6661092  0.4129135 -2.4141838


In [67]:
b <- matrix ("foo", ncol=3, nrow=5)

In [68]:
print(b)

     [,1]  [,2]  [,3] 
[1,] "foo" "foo" "foo"
[2,] "foo" "foo" "foo"
[3,] "foo" "foo" "foo"
[4,] "foo" "foo" "foo"
[5,] "foo" "foo" "foo"


## Indexing in Matrices

In [69]:
dat <- sample(12)

In [70]:
m <- matrix(dat, ncol=3)

In [71]:
print(m)

     [,1] [,2] [,3]
[1,]    4    8    9
[2,]   11    2    5
[3,]   10    1   12
[4,]    3    6    7


In [73]:
m[2,3] #second row, third column

[1] 5

In [75]:
m[1:2,3] #first and second in third colomn 

[1] 9 5

In [80]:
m[1, ] #numbers in the first row, already changed afterwards

[1]  4 99  0

In [77]:
m[ ,3] <- 0 #numbers in the thrid column

In [78]:
print (m)

     [,1] [,2] [,3]
[1,]    4    8    0
[2,]   11    2    0
[3,]   10    1    0
[4,]    3    6    0


In [79]:
m[1:2,2] <- 99 
print (m)

     [,1] [,2] [,3]
[1,]    4   99    0
[2,]   11   99    0
[3,]   10    1    0
[4,]    3    6    0


In [81]:
num_rows <- nrow(m)

In [82]:
print(num_rows)

[1] 4


In [83]:
colMeans(m)

[1]  7.00 51.25  0.00

In [84]:
colSums(m)

[1]  28 205   0

In [85]:
rowSums(m)

[1] 103 110  11   9

## The DataFrame

In [87]:
id <- seq(4)

In [88]:
score <- rnorm(4)

In [89]:
names <- c("john","paul","george","ringo")

In [90]:
vocals <- c(TRUE, TRUE, FALSE, FALSE)

In [92]:
dset <- data.frame(id, names, score, vocals)

In [93]:
print (dset)

  id  names      score vocals
1  1   john  0.9928254   TRUE
2  2   paul -0.6035269   TRUE
3  3 george -0.3304287  FALSE
4  4  ringo -1.1116355  FALSE


In [94]:
dset [1, 2]

[1] john
Levels: george john paul ringo

In [95]:
dset $ names #entire column of Names 

[1] john   paul   george ringo 
Levels: george john paul ringo